routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

/*
|--------------------------------------------------------------------------
| Auth Login Route
|--------------------------------------------------------------------------
*/
Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');

Route::post('login', 'Auth\LoginController@login');

Route::get('activate', 'AuthController@verifyAccount');

Route::post('set-password', 'AuthController@setPassword');

Route::group(['middleware' => ['auth', 'validate.user', 'user.activated']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/users-work-report', 'HomeController@workReport')->name('users-work-report');
    Route::get('/developer-work-report', 'HomeController@developerWorkReport')->name('developers-work-report');

    Route::post('logout', 'Auth\LoginController@logout');
    Route::group(['middleware' => ['permission:manage_activities']], function () {
        Route::resource('activity-types', 'ActivityTypeController');
    });

    Route::group(['middleware' => ['permission:manage_clients']], function () {
        Route::resource('clients', 'ClientController');
    });

    Route::group(['middleware' => ['permission:manage_users']], function () {
        Route::post('users/{user}/active-de-active', 'UserController@activeDeActiveUser')
            ->name('active-de-active-user');
        Route::resource('users', 'UserController');
        Route::get('users/{user}/send-email', 'UserController@resendEmailVerification')->name('send-email');
    });

    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::post('users/profile-update', 'UserController@profileUpdate')->name('update-profile');
    Route::post('users/change-password', 'UserController@changePassword')->name('change-password');

    Route::group(['middleware' => ['permission:manage_tags']], function () {
        Route::resource('tags', 'TagController');
    });

    Route::group(['middleware' => ['permission:manage_projects']], function () {
        Route::resource('projects', 'ProjectController');
    });

    Route::group(['middleware' => ['permission:manage_all_tasks']], function () {
        Route::resource('tasks', 'TaskController');
        Route::post('tasks/{task}/update-status', 'TaskController@updateStatus')->name('task.update-status');
        Route::post('tasks/{task}/add-attachment', 'TaskController@addAttachment')->name('task.add-attachment');
        Route::post('tasks/{task_attachment}/delete-attachment', 'TaskController@deleteAttachment')
            ->name('task.delete-attachment');
        Route::get('tasks/{task}/get-attachments', 'TaskController@getAttachment')->name('task.attachments');
        Route::post('tasks/{task}/comments', 'CommentController@addComment')->name('task.comments');
        Route::post(
            'tasks/{task}/comments/{comment}/update',
            'CommentController@editComment'
        )->name('task.update-comment');
        Route::delete(
            'tasks/{task}/comments/{comment}',
            'CommentController@deleteComment'
        )->name('task.delete-comment');
        Route::get('task-details/{task}', 'TaskController@getTaskDetails')->name('task.get-details');
        Route::get('tasks/{task}/comments-count', 'TaskController@getCommentsCount')->name('task.comments-count');
        Route::get('tasks/{task}/users', 'TaskController@getTaskUsers')->name('task.users');
    });

    Route::resource('time-entries', 'TimeEntryController');
    Route::post('time-entries/{time_entry}/update', 'TimeEntryController@update');
    Route::post('start-timer', 'TimeEntryController@getStartTimer');

    Route::group(['middleware' => ['permission:manage_reports']], function () {
        Route::resource('reports', 'ReportController');
        Route::get('users-of-projects', 'ProjectController@users')->name('users-of-projects');
        Route::get('projects-of-client', 'ClientController@projects')->name('projects-of-client');
        Route::get('clients-of-department', 'DepartmentController@clients')->name('clients-of-department');
    });

    Route::get('my-tasks', 'TaskController@myTasks')->name('my-tasks');
    Route::get('user-last-task-work', 'TimeEntryController@getUserLastTask')->name('user-last-task-work');
    Route::get('projects/{project}/tasks', 'TimeEntryController@getTasks')->name('project-tasks');
    Route::get('my-projects', 'ProjectController@getMyProjects')->name('my-projects');

    Route::group(['middleware' => ['permission:manage_roles']], function () {
        Route::resource('roles', 'RoleController');
    });

    Route::group(['middleware' => ['permission:manage_department']], function () {
        Route::resource('departments', 'DepartmentController');
        Route::post('departments/{department}/update', 'DepartmentController@update');
    });
});

Route::fallback(function () {
    abort(\Symfony\Component\HttpFoundation\Response::HTTP_NOT_FOUND);
});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Models\Tag.
 *
 * @property int $id
 * @property string $name
 * @property int|null $created_by
 * @property int $deleted_by
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Models\User|null $createdUser
 *
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Tag newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Tag newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Tag query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Tag whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Tag whereCreatedBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Tag whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Tag whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Tag whereUpdatedAt($value)
 * @mixin \Eloquent
 *
 * @property \Illuminate\Support\Carbon|null $deleted_at
 *
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Tag onlyTrashed()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Tag whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Tag whereDeletedBy($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Tag withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Tag withoutTrashed()
 */
class Tag extends Model
{
    use softDeletes;
    public $table = 'tags';

    public $fillable = [
        'name',
        'created_by',
        'deleted_by',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id'         => 'integer',
        'name'       => 'string',
        'created_by' => 'integer',
        'deleted_by' => 'integer',
    ];

    /**
     * Validation rules.
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required|unique:tags,name',
    ];

    /**
     * @return BelongsTo
     */
    public function createdUser()
    {
        return $this->belongsTo(User::class, 'created_by');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTagRequest;
use App\Http\Requests\UpdateTagRequest;
use App\Models\Tag;
use App\Queries\TagDataTable;
use App\Repositories\TagRepository;
use DataTables;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

/**
 * Class TagController.
 */
class TagController extends AppBaseController
{
    /** @var TagRepository */
    private $tagRepository;

    /**
     * TagController constructor.
     *
     * @param TagRepository $tagRepo
     */
    public function __construct(TagRepository $tagRepo)
    {
        $this->tagRepository = $tagRepo;
    }

    /**
     * @param Request $request
     *
     * @throws Exception
     *
     * @return Factory|View
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return DataTables::of((new TagDataTable())->get($request->only(['name'])))->make(true);
        }

        return view('tags.index');
    }

    /**
     * Store a newly created Tag in storage.
     *
     * @param CreateTagRequest $request
     *
     * @return JsonResponse
     */
    public function store(CreateTagRequest $request)
    {
        $input = $request->all();

        $this->tagRepository->store($input);

        return $this->sendSuccess('Tag created successfully.');
    }

    /**
     * Show the form for editing the specified Tag.
     *
     * @param Tag $tag
     *
     * @return JsonResponse
     */
    public function edit(Tag $tag)
    {
        return $this->sendResponse($tag, 'Tag retrieved successfully.');
    }

    /**
     * Update the specified Tag in storage.
     *
     * @param Tag              $tag
     * @param UpdateTagRequest $request
     *
     * @return JsonResponse
     */
    public function update(Tag $tag, UpdateTagRequest $request)
    {
        $this->tagRepository->update($request->all(), $tag->id);

        return $this->sendSuccess('Tag updated successfully.');
    }

    /**
     * Remove the specified Tag from storage.
     *
     * @param Tag $tag
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function destroy(Tag $tag)
    {
        $tag->deleted_by = getLoggedInUserId();
        $tag->save();
        $tag->delete();

        return $this->sendSuccess('Tag deleted successfully.');
    }
}

resources/views/tags/edit_modal.blade.php
<div id="EditModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Tag</h5>
                <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
            </div>
            {!! Form::open(['id'=>'editForm']) !!}
            <div class="modal-body">
                <div class="alert alert-danger" id="editValidationErrorsBox"style="display: none" ></div>
                {!! Form::hidden('tag_id',null,['id'=>'tagId']) !!}
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('name', 'Name') !!}<span class="required">*</span>
                        {!! Form::text('name', null, ['id'=>'tagName','class' => 'form-control','required']) !!}
                    </div>
                </div>
                <div class="text-right">
                    {!! Form::button('Save', ['type'=>'submit','class' => 'btn btn-primary','id'=>'btnEditSave','data-loading-text'=>"<span class='spinner-border spinner-border-sm'></span> Processing..."]) !!}
                    <button type="button" class="btn btn-light ml-1" data-dismiss="modal">Cancel</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/tags/index.blade.php
@extends('layouts.app')
@section('title')
    Tags
@endsection

@section('content')
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
            <div class="page-header">
                <h3 class="page__heading">Tags</h3>
                <div style="display: flex;align-items: center">
                    <a href="#" class="btn btn-primary" onclick="setBulkTags()" data-toggle="modal"
                       data-target="#AddModal"></i>Bulk Tags</a>
                    &nbsp;
                    <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#AddModal"></i>New Tag</a>
                </div>
            </div>
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-body">
                             @include('tags.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                         @include('tags.modal')
                         @include('tags.edit_modal')
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

@section('scripts')
    <script>
       let tagCreateUrl='{{route('tags.store')}}';
       let tagUrl='{{url('tags')}}/';
    </script>
    <script src="{{ mix('assets/js/tags/tag.js') }}"></script>
@endsection

resources/views/tags/modal.blade.php
<div id="AddModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="tagHeader">New Tag</h5>
                <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
            </div>
            {!! Form::open(['id'=>'addNewForm']) !!}
            <input type="hidden" name='bulk_tags' id=isBulkTags>
            <div class="modal-body">
                <div class="alert alert-danger" id="validationErrorsBox" style="display: none"></div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('name', 'Name') !!}<span class="required">*</span>
                        {!! Form::text('name', null, ['id'=>'name','class' => 'form-control','required']) !!}
                    </div>
                </div>
                <div class="text-right">
                    {!! Form::button('Save', ['type'=>'submit','class' => 'btn btn-primary','id'=>'btnSave','data-loading-text'=>"<span class='spinner-border spinner-border-sm'></span> Processing..."]) !!}
                    <button type="button" class="btn btn-light ml-1" data-dismiss="modal">Cancel</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/tags/table.blade.php
<table class="table table-responsive-sm table-striped table-bordered" id="tags_table" tabindex="-1">
    <thead>
    <tr>
        <th>Name</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>