routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

/*
|--------------------------------------------------------------------------
| Auth Login Route
|--------------------------------------------------------------------------
*/
Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');

Route::post('login', 'Auth\LoginController@login');

Route::get('activate', 'AuthController@verifyAccount');

Route::post('set-password', 'AuthController@setPassword');

Route::group(['middleware' => ['auth', 'validate.user', 'user.activated']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/users-work-report', 'HomeController@workReport')->name('users-work-report');
    Route::get('/developer-work-report', 'HomeController@developerWorkReport')->name('developers-work-report');

    Route::post('logout', 'Auth\LoginController@logout');
    Route::group(['middleware' => ['permission:manage_activities']], function () {
        Route::resource('activity-types', 'ActivityTypeController');
    });

    Route::group(['middleware' => ['permission:manage_clients']], function () {
        Route::resource('clients', 'ClientController');
    });

    Route::group(['middleware' => ['permission:manage_users']], function () {
        Route::post('users/{user}/active-de-active', 'UserController@activeDeActiveUser')
            ->name('active-de-active-user');
        Route::resource('users', 'UserController');
        Route::get('users/{user}/send-email', 'UserController@resendEmailVerification')->name('send-email');
    });

    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::post('users/profile-update', 'UserController@profileUpdate')->name('update-profile');
    Route::post('users/change-password', 'UserController@changePassword')->name('change-password');

    Route::group(['middleware' => ['permission:manage_tags']], function () {
        Route::resource('tags', 'TagController');
    });

    Route::group(['middleware' => ['permission:manage_projects']], function () {
        Route::resource('projects', 'ProjectController');
    });

    Route::group(['middleware' => ['permission:manage_all_tasks']], function () {
        Route::resource('tasks', 'TaskController');
        Route::post('tasks/{task}/update-status', 'TaskController@updateStatus')->name('task.update-status');
        Route::post('tasks/{task}/add-attachment', 'TaskController@addAttachment')->name('task.add-attachment');
        Route::post('tasks/{task_attachment}/delete-attachment', 'TaskController@deleteAttachment')
            ->name('task.delete-attachment');
        Route::get('tasks/{task}/get-attachments', 'TaskController@getAttachment')->name('task.attachments');
        Route::post('tasks/{task}/comments', 'CommentController@addComment')->name('task.comments');
        Route::post(
            'tasks/{task}/comments/{comment}/update',
            'CommentController@editComment'
        )->name('task.update-comment');
        Route::delete(
            'tasks/{task}/comments/{comment}',
            'CommentController@deleteComment'
        )->name('task.delete-comment');
        Route::get('task-details/{task}', 'TaskController@getTaskDetails')->name('task.get-details');
        Route::get('tasks/{task}/comments-count', 'TaskController@getCommentsCount')->name('task.comments-count');
        Route::get('tasks/{task}/users', 'TaskController@getTaskUsers')->name('task.users');
    });

    Route::resource('time-entries', 'TimeEntryController');
    Route::post('time-entries/{time_entry}/update', 'TimeEntryController@update');
    Route::post('start-timer', 'TimeEntryController@getStartTimer');

    Route::group(['middleware' => ['permission:manage_reports']], function () {
        Route::resource('reports', 'ReportController');
        Route::get('users-of-projects', 'ProjectController@users')->name('users-of-projects');
        Route::get('projects-of-client', 'ClientController@projects')->name('projects-of-client');
        Route::get('clients-of-department', 'DepartmentController@clients')->name('clients-of-department');
    });

    Route::get('my-tasks', 'TaskController@myTasks')->name('my-tasks');
    Route::get('user-last-task-work', 'TimeEntryController@getUserLastTask')->name('user-last-task-work');
    Route::get('projects/{project}/tasks', 'TimeEntryController@getTasks')->name('project-tasks');
    Route::get('my-projects', 'ProjectController@getMyProjects')->name('my-projects');

    Route::group(['middleware' => ['permission:manage_roles']], function () {
        Route::resource('roles', 'RoleController');
    });

    Route::group(['middleware' => ['permission:manage_department']], function () {
        Route::resource('departments', 'DepartmentController');
        Route::post('departments/{department}/update', 'DepartmentController@update');
    });
});

Route::fallback(function () {
    abort(\Symfony\Component\HttpFoundation\Response::HTTP_NOT_FOUND);
});

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ChangePasswordRequest;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserProfileRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\User;
use App\Queries\UserDataTable;
use App\Repositories\ProjectRepository;
use App\Repositories\RoleRepository;
use App\Repositories\UserRepository;
use DataTables;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\View\View;

/**
 * Class UserController.
 */
class UserController extends AppBaseController
{
    /** @var UserRepository */
    private $userRepository;

    /**
     * UserController constructor.
     *
     * @param UserRepository $userRepo
     */
    public function __construct(UserRepository $userRepo)
    {
        $this->userRepository = $userRepo;
    }

    /**
     * Display a listing of the User.
     *
     * @param Request           $request
     * @param RoleRepository    $roleRepository
     * @param ProjectRepository $projectRepository
     *
     * @throws Exception
     *
     * @return Factory|View
     */
    public function index(Request $request, RoleRepository $roleRepository, ProjectRepository $projectRepository)
    {
        if ($request->ajax()) {
            return Datatables::of((new UserDataTable())->get())->addColumn('role_name', function (User $user) {
                return implode(',', $user->roles()->pluck('name')->toArray());
            })->make(true);
        }

        $projects = $projectRepository->getProjectsList();
        $roles = $roleRepository->getRolesList();

        return view('users.index')->with(['projects' => $projects, 'roles' => $roles]);
    }

    /**
     * Store a newly created User in storage.
     *
     * @param CreateUserRequest $request
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function store(CreateUserRequest $request)
    {
        $input = $request->all();

        $this->userRepository->store($input);

        return $this->sendSuccess('User created successfully.');
    }

    /**
     * Show the form for editing the specified User.
     *
     * @param User $user
     *
     * @return JsonResponse
     */
    public function edit(User $user)
    {
        $userObj = $user->toArray();
        $userObj['project_ids'] = $user->projects()->pluck('project_id')->toArray();
        $userObj['role_id'] = $user->roles()->pluck('role_id')->toArray();

        return $this->sendResponse($userObj, 'User retrieved successfully.');
    }

    /**
     * Update the specified User in storage.
     *
     * @param User              $user
     * @param UpdateUserRequest $request
     *
     * @throws Exception
     *
     * @return JsonResponse|RedirectResponse
     */
    public function update(User $user, UpdateUserRequest $request)
    {
        $input = $request->all();

        $this->userRepository->update($input, $user->id);

        return $this->sendSuccess('User updated successfully.');
    }

    /**
     * Remove the specified User from storage.
     *
     * @param User $user
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function destroy(User $user)
    {
        $user->deleted_by = getLoggedInUserId();
        $user->save();
        $user->delete();

        return $this->sendSuccess('User deleted successfully.');
    }

    /**
     * @param User $user
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function resendEmailVerification(User $user)
    {
        $this->userRepository->resendEmailVerification($user->id);

        return $this->sendSuccess('Verification email has been sent successfully.');
    }

    /**
     * @param UpdateUserProfileRequest $request
     *
     * @return JsonResponse
     */
    public function profileUpdate(UpdateUserProfileRequest $request)
    {
        $input = $request->all();

        $this->userRepository->profileUpdate($input);

        return $this->sendSuccess('Profile updated successfully.');
    }

    /**
     * @param ChangePasswordRequest $request
     *
     * @return JsonResponse
     */
    public function changePassword(ChangePasswordRequest $request)
    {
        $input = $request->all();

        /** @var User $user */
        $user = Auth::user();

        if (!Hash::check($input['password_current'], $user->password)) {
            return $this->sendError('Current password is invalid.');
        }

        $input['password'] = Hash::make($input['password']);
        $user->update($input);

        return $this->sendSuccess('Password updated successfully.');
    }

    /**
     * @param User $user
     *
     * @return JsonResponse
     */
    public function activeDeActiveUser(User $user)
    {
        $this->userRepository->activeDeActiveUser($user->id);

        return $this->sendSuccess('User updated successfully.');
    }
}

resources/views/users/edit_modal.blade.php
<div id="EditModal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit User</h5>
                <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
            </div>
            {!! Form::open(['id'=>'editForm','files'=>true]) !!}
            <div class="modal-body">
                <div class="alert alert-danger" style="display: none" id="editValidationErrorsBox"></div>
                {!! Form::hidden('user_id',null,['id'=>'userId']) !!}
                <div class="row">
                    <div class="form-group col-sm-6">
                        {!! Form::label('name', 'Name') !!}<span class="required">*</span>
                        {!! Form::text('name', null, ['id'=>'edit_name','class' => 'form-control','required']) !!}
                    </div>
                    <div class="form-group col-sm-6">
                        {!! Form::label('phone', 'Phone') !!}
                        {!! Form::number('phone', null, ['id'=>'edit_phone','class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('email', 'Email') !!}<span class="required">*</span>
                        {!! Form::email('email', null, ['id'=>'edit_email','class' => 'form-control','required',"autocomplete"=>"new-password"]) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('salary', 'Salary') !!}
                        {!! Form::number('salary', null, ['id'=>'edit_salary','class' => 'form-control','min'=>'0']) !!}
                    </div>
                </div>
                @can('manage_users')
                    <div class="row">
                        <div class="form-group col-sm-6">
                            {!! Form::label('password', 'New Password') !!}<span class="required confirm-pwd">*</span>
                            <div class="input-group">
                                <input class="form-control input-group__addon" id="edit_password" type="password"
                                       name="password" autocomplete="new-password">
                                <div class="input-group-append input-group__icon">
                                <span class="input-group-text changeType">
                                    <i class="icon-ban icons"></i>
                                </span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-sm-6">
                            {!! Form::label('password_confirmation', 'Confirm Password') !!}<span
                                class="required confirm-pwd">*</span>
                            <div class="input-group">
                                <input class="form-control input-group__addon" id="edit_confirm_password"
                                       type="password" name="password_confirmation" autocomplete="password_confirmation">
                                <div class="input-group-append input-group__icon">
                                <span class="input-group-text changeType">
                                    <i class="icon-ban icons"></i>
                                </span>
                                </div>
                            </div>
                        </div>
                    </div>
                @endcan
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('project_id', 'Project') !!}
                        {!! Form::select('project_ids[]', $projects, null, ['class' => 'form-control','id' => 'editProjectId', 'multiple'=>true]) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('active', 'Active') !!}
                        <label class="switch switch-label switch-outline-primary-alt d-block">
                            <input name="is_active" class="switch-input" id="edit_is_active" type="checkbox">
                            <span class="switch-slider" data-checked="&#x2713;" data-unchecked="&#x2715;"></span>
                        </label>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('role_id', 'Role') !!}
                        {!! Form::select('role_id', $roles, null, ['class' => 'form-control', 'id' => 'editRoleId']) !!}
                    </div>
                </div>
                <div class="text-right">
                    {!! Form::button('Save', ['type'=>'submit','class' => 'btn btn-primary','id'=>'btnEditSave','data-loading-text'=>"<span class='spinner-border spinner-border-sm'></span> Processing..."]) !!}
                    <button type="button" class="btn btn-light ml-1" data-dismiss="modal">Cancel</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/users/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Website Field -->
<div class="form-group col-sm-6">
    {!! Form::label('website', 'Website:') !!}
    {!! Form::text('website', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('clients.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/users/index.blade.php
@extends('layouts.app')
@section('title')
    Users
@endsection
@section('content')
    <div class="container-fluid">
        <div class="animated fadeIn">
            @include('flash::message')
            <div class="page-header">
                <h3 class="page__heading">Users</h3>
                <div style="display: flex;align-items: center">
                    <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#AddModal"></i>New
                        User</a>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            @include('users.table')
                            <div class="pull-right mr-3">

                            </div>
                        </div>
                        @include('users.modal')
                        @include('users.edit_modal')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        let createUserUrl = "{{ route('users.store') }}";
    </script>
    <script src="{{ mix('assets/js/users/user.js') }}"></script>
@endsection

resources/views/users/modal.blade.php
<div id="AddModal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">New User</h5>
                <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
            </div>
            {!! Form::open(['id'=>'addNewForm','files'=>true]) !!}
            <div class="modal-body">
                <div class="alert alert-danger" style="display: none" id="validationErrorsBox"></div>
                <div class="row">
                    <div class="form-group col-sm-6">
                        {!! Form::label('name', 'Name') !!}<span class="required">*</span>
                        {!! Form::text('name', null, ['id'=>'name','class' => 'form-control','required']) !!}
                    </div>
                    <div class="form-group col-sm-6">
                        {!! Form::label('phone', 'Phone') !!}
                        {!! Form::number('phone', null, ['id'=>'phone','class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('email', 'Email') !!}<span class="required">*</span>
                        {!! Form::email('email', null, ['id'=>'email','class' => 'form-control','required']) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('salary', 'Salary') !!}
                        {!! Form::number('salary', null, ['id'=>'salary','class' => 'form-control']) !!}
                    </div>
                </div>
                @can('manage_users')
                    <div class="row">
                        <div class="form-group col-sm-6">
                            {!! Form::label('password', 'New Password') !!}<span class="required confirm-pwd">*</span>
                            <div class="input-group">
                                <input class="form-control input-group__addon" id="new_password" type="password" name="password">
                                <div class="input-group-append input-group__icon">
                                <span class="input-group-text changeType">
                                    <i class="icon-ban icons"></i>
                                </span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-sm-6">
                            {!! Form::label('password_confirmation', 'Confirm Password') !!}<span class="required confirm-pwd">*</span>
                            <div class="input-group">
                                <input class="form-control input-group__addon" id="new_confirm_password" type="password" name="password_confirmation">
                                <div class="input-group-append input-group__icon">
                                <span class="input-group-text changeType">
                                    <i class="icon-ban icons"></i>
                                </span>
                                </div>
                            </div>
                        </div>
                    </div>
                @endcan
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('project_id', 'Project') !!}
                        {!! Form::select('project_ids[]', $projects, null, ['class' => 'form-control', 'id' => 'projectId','multiple'=>true]) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('role_id', 'Role') !!}<span class="required">*</span>
                        {!! Form::select('role_id', $roles, null, ['class' => 'form-control', 'id' => 'roleId','placeholder'=>'Select Role', 'required']) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('active', 'Active') !!}
                        <label class="switch switch-label switch-outline-primary-alt d-block">
                            <input name="is_active" class="switch-input" type="checkbox" value="1" checked="">
                            <span class="switch-slider" data-checked="&#x2713;" data-unchecked="&#x2715;"></span>
                        </label>
                    </div>
                </div>
                <div class="text-right">
                    {!! Form::button('Save', ['type'=>'submit','class' => 'btn btn-primary','id'=>'btnSave','data-loading-text'=>"<span class='spinner-border spinner-border-sm'></span> Processing..."]) !!}
                    <button type="button" class="btn btn-light ml-1" data-dismiss="modal">Cancel</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/users/table.blade.php
<table class="table table-responsive-sm table-striped table-bordered" id="users_table">
    <thead>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Role</th>
        <th>Salary</th>
        <th>Active</th>
        <th>Is Email Verified</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>