routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

/*
|--------------------------------------------------------------------------
| Auth Login Route
|--------------------------------------------------------------------------
*/
Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');

Route::post('login', 'Auth\LoginController@login');

Route::get('activate', 'AuthController@verifyAccount');

Route::post('set-password', 'AuthController@setPassword');

Route::group(['middleware' => ['auth', 'validate.user', 'user.activated']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/users-work-report', 'HomeController@workReport')->name('users-work-report');
    Route::get('/developer-work-report', 'HomeController@developerWorkReport')->name('developers-work-report');

    Route::post('logout', 'Auth\LoginController@logout');
    Route::group(['middleware' => ['permission:manage_activities']], function () {
        Route::resource('activity-types', 'ActivityTypeController');
    });

    Route::group(['middleware' => ['permission:manage_clients']], function () {
        Route::resource('clients', 'ClientController');
    });

    Route::group(['middleware' => ['permission:manage_users']], function () {
        Route::post('users/{user}/active-de-active', 'UserController@activeDeActiveUser')
            ->name('active-de-active-user');
        Route::resource('users', 'UserController');
        Route::get('users/{user}/send-email', 'UserController@resendEmailVerification')->name('send-email');
    });

    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::post('users/profile-update', 'UserController@profileUpdate')->name('update-profile');
    Route::post('users/change-password', 'UserController@changePassword')->name('change-password');

    Route::group(['middleware' => ['permission:manage_tags']], function () {
        Route::resource('tags', 'TagController');
    });

    Route::group(['middleware' => ['permission:manage_projects']], function () {
        Route::resource('projects', 'ProjectController');
    });

    Route::group(['middleware' => ['permission:manage_all_tasks']], function () {
        Route::resource('tasks', 'TaskController');
        Route::post('tasks/{task}/update-status', 'TaskController@updateStatus')->name('task.update-status');
        Route::post('tasks/{task}/add-attachment', 'TaskController@addAttachment')->name('task.add-attachment');
        Route::post('tasks/{task_attachment}/delete-attachment', 'TaskController@deleteAttachment')
            ->name('task.delete-attachment');
        Route::get('tasks/{task}/get-attachments', 'TaskController@getAttachment')->name('task.attachments');
        Route::post('tasks/{task}/comments', 'CommentController@addComment')->name('task.comments');
        Route::post(
            'tasks/{task}/comments/{comment}/update',
            'CommentController@editComment'
        )->name('task.update-comment');
        Route::delete(
            'tasks/{task}/comments/{comment}',
            'CommentController@deleteComment'
        )->name('task.delete-comment');
        Route::get('task-details/{task}', 'TaskController@getTaskDetails')->name('task.get-details');
        Route::get('tasks/{task}/comments-count', 'TaskController@getCommentsCount')->name('task.comments-count');
        Route::get('tasks/{task}/users', 'TaskController@getTaskUsers')->name('task.users');
    });

    Route::resource('time-entries', 'TimeEntryController');
    Route::post('time-entries/{time_entry}/update', 'TimeEntryController@update');
    Route::post('start-timer', 'TimeEntryController@getStartTimer');

    Route::group(['middleware' => ['permission:manage_reports']], function () {
        Route::resource('reports', 'ReportController');
        Route::get('users-of-projects', 'ProjectController@users')->name('users-of-projects');
        Route::get('projects-of-client', 'ClientController@projects')->name('projects-of-client');
        Route::get('clients-of-department', 'DepartmentController@clients')->name('clients-of-department');
    });

    Route::get('my-tasks', 'TaskController@myTasks')->name('my-tasks');
    Route::get('user-last-task-work', 'TimeEntryController@getUserLastTask')->name('user-last-task-work');
    Route::get('projects/{project}/tasks', 'TimeEntryController@getTasks')->name('project-tasks');
    Route::get('my-projects', 'ProjectController@getMyProjects')->name('my-projects');

    Route::group(['middleware' => ['permission:manage_roles']], function () {
        Route::resource('roles', 'RoleController');
    });

    Route::group(['middleware' => ['permission:manage_department']], function () {
        Route::resource('departments', 'DepartmentController');
        Route::post('departments/{department}/update', 'DepartmentController@update');
    });
});

Route::fallback(function () {
    abort(\Symfony\Component\HttpFoundation\Response::HTTP_NOT_FOUND);
});

app/Models/Client.php
<?php

namespace App\Models;

use Eloquent;
use Illuminate\Database\Eloquent\Builder as BuilderAlias;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Query\Builder;
use Illuminate\Support\Carbon;

/**
 * App\Models\Client.
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $website
 * @property int $deleted_by
 * @property int|null $created_by
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read User|null $createdUser
 *
 * @method static BuilderAlias|Client newModelQuery()
 * @method static BuilderAlias|Client newQuery()
 * @method static BuilderAlias|Client query()
 * @method static BuilderAlias|Client whereCreatedAt($value)
 * @method static BuilderAlias|Client whereCreatedBy($value)
 * @method static BuilderAlias|Client whereEmail($value)
 * @method static BuilderAlias|Client whereId($value)
 * @method static BuilderAlias|Client whereName($value)
 * @method static BuilderAlias|Client whereUpdatedAt($value)
 * @method static BuilderAlias|Client whereWebsite($value)
 * @mixin Eloquent
 *
 * @property Carbon|null $deleted_at
 * @property-read Collection|Project[] $projects
 * @property-read int|null $projects_count
 *
 * @method static bool|null forceDelete()
 * @method static Builder|Client onlyTrashed()
 * @method static bool|null restore()
 * @method static BuilderAlias|Client whereDeletedAt($value)
 * @method static BuilderAlias|Client whereDeletedBy($value)
 * @method static Builder|Client withTrashed()
 * @method static Builder|Client withoutTrashed()
 *
 * @property int|null $department_id
 * @property-read \App\Models\Department|null $department
 *
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Client whereDepartmentId($value)
 */
class Client extends Model
{
    use softDeletes;
    public $table = 'clients';

    public $fillable = [
        'name',
        'email',
        'website',
        'department_id',
        'created_by',
        'deleted_by',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id'            => 'integer',
        'name'          => 'string',
        'email'         => 'string',
        'website'       => 'string',
        'deleted_by'    => 'integer',
        'department_id' => 'integer',
    ];

    /**
     * Validation rules.
     *
     * @var array
     */
    public static $rules = [
        'name'          => 'required|unique:clients,name',
        'email'         => 'nullable|email|regex:/^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-z0-9]{2,4}$/',
        'website'       => 'nullable|regex:/^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/',
        'department_id' => 'required|integer',
    ];

    public static $editRules = [
        'email'         => 'nullable|email|regex:/^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-z0-9]{2,4}$/',
        'website'       => 'nullable|regex:/^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/',
        'department_id' => 'required|integer',
    ];

    public static $messages = [
        'website.regex'          => 'Please enter valid url.',
        'email.regex'            => 'Please enter valid email.',
        'department_id.required' => 'Please select valid department.',
    ];

    /**
     * @return BelongsTo
     */
    public function createdUser()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * @return HasMany
     */
    public function projects()
    {
        return $this->hasMany(Project::class);
    }

    /**
     * @return BelongsTo
     */
    public function department()
    {
        return $this->belongsTo(Department::class);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateClientRequest;
use App\Http\Requests\UpdateClientRequest;
use App\Models\Client;
use App\Models\Department;
use App\Queries\ClientDataTable;
use App\Repositories\ClientRepository;
use App\Repositories\ProjectRepository;
use DataTables;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

/**
 * Class ClientController.
 */
class ClientController extends AppBaseController
{
    /** @var ClientRepository */
    private $clientRepository;

    /**
     * ClientController constructor.
     *
     * @param ClientRepository $clientRepo
     */
    public function __construct(ClientRepository $clientRepo)
    {
        $this->clientRepository = $clientRepo;
    }

    /**
     * Display a listing of the Client.
     *
     * @param Request $request
     *
     * @throws Exception
     *
     * @return Factory|View
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return Datatables::of((new ClientDataTable())->get($request->only(['filter_department'])))->make(true);
        }
        $departments = Department::all()->pluck('name', 'id')->toArray();

        return view('clients.index', ['departments' => $departments]);
    }

    /**
     * Store a newly created Client in storage.
     *
     * @param CreateClientRequest $request
     *
     * @return JsonResponse
     */
    public function store(CreateClientRequest $request)
    {
        $input = $request->all();
        $input['created_by'] = getLoggedInUserId();

        $this->clientRepository->create($this->fill($input));

        return $this->sendSuccess('Client created successfully.');
    }

    /**
     * @param array $input
     *
     * @return mixed
     */
    public function fill($input)
    {
        $input['email'] = is_null($input['email']) ? '' : $input['email'];
        $input['website'] = is_null($input['website']) ? '' : $input['website'];

        return $input;
    }

    /**
     * Show the form for editing the specified Client.
     *
     * @param Client $client
     *
     * @return JsonResponse
     */
    public function edit(Client $client)
    {
        return $this->sendResponse($client, 'Client retrieved successfully.');
    }

    /**
     * Update the specified Client in storage.
     *
     * @param Client              $client
     * @param UpdateClientRequest $request
     *
     * @return JsonResponse
     */
    public function update(Client $client, UpdateClientRequest $request)
    {
        $this->clientRepository->update($this->fill($request->all()), $client->id);

        return $this->sendSuccess('Client updated successfully.');
    }

    /**
     * Remove the specified Client from storage.
     *
     * @param Client $client
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function destroy(Client $client)
    {
        $this->clientRepository->delete($client->id);

        return $this->sendSuccess('Client deleted successfully.');
    }

    /**
     * @param Request           $request
     * @param ProjectRepository $projectRepository
     *
     * @return JsonResponse
     */
    public function projects(Request $request, ProjectRepository $projectRepository)
    {
        $projects = $projectRepository->getProjectsList($request->get('client_id', null));

        return $this->sendResponse($projects, 'Projects retrieved successfully.');
    }
}

resources/views/clients/edit_modal.blade.php
<div id="EditModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Client</h5>
                <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
            </div>
            {!! Form::open(['id' => 'editForm', 'files' => true]) !!}
            <div class="modal-body">
                <div class="alert alert-danger" style="display: none" id="editValidationErrorsBox"></div>
                {!! Form::hidden('client_id', null, ['id' => 'clientId']) !!}
                <div class="row">
                    <div class="form-group col-sm-6">
                        {!! Form::label('name', 'Name') !!}<span class="required">*</span>
                        {!! Form::text('name', '', ['id' => 'edit_name', 'class' => 'form-control', 'required']) !!}
                    </div>
                    <div class="form-group col-sm-6">
                        {!! Form::label('department_id', 'Department') !!}<span class="required">*</span>
                        {!! Form::select('department_id', $departments, null, ['id' => 'edit_department_id', 'class' => 'form-control', 'required']) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('email', 'Email') !!}
                        {!! Form::email('email', '', ['id' => 'edit_email', 'class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('website', 'Website') !!}
                        {!! Form::url('website', '', ['id' => 'edit_website', 'class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="text-right">
                    {!! Form::button('Save', ['type' => 'submit', 'class' => 'btn btn-primary', 'id' => 'btnEditSave', 'data-loading-text' => "<span class='spinner-border spinner-border-sm'></span> Processing..."]) !!}
                    <button type="button" class="btn btn-light ml-1" data-dismiss="modal">Cancel</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/clients/index.blade.php
@extends('layouts.app')
@section('title')
    Clients
@endsection

@section('content')
    <div class="container-fluid">
        <div class="animated fadeIn">
            @include('flash::message')
            <div class="page-header">
                <h3 class="page__heading">Clients</h3>
                <div class="filter-container">
                    <div class="mr-2">
                        <label class="lbl-block"><b>Department</b></label>
                        {!!Form::select('department_id', $departments, Auth::id(), ['id' => 'filter_department', 'class'=>'form-control', 'placeholder' => 'All'])  !!}
                    </div>
                    <a href="#" class="btn btn-primary filter-container__btn" data-toggle="modal" data-target="#AddModal"></i>New Client</a>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            @include('clients.table')
                            <div class="pull-right mr-3">

                            </div>
                        </div>
                        @include('clients.modal')
                        @include('clients.edit_modal')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        let clientCreateUrl = "{{ route('clients.store') }}";
        let clientUrl = "{{url('clients')}}/";
    </script>
    <script src="{{ mix('assets/js/clients/client.js') }}"></script>
@endsection

resources/views/clients/modal.blade.php
<div id="AddModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">New Client</h5>
                <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
            </div>
            {!! Form::open(['id' => 'addNewForm', 'files' => true]) !!}
            <div class="modal-body">
                <div class="alert alert-danger" style="display: none" id="validationErrorsBox"></div>
                <div class="row">
                    <div class="form-group col-sm-6">
                        {!! Form::label('name', 'Name') !!}<span class="required">*</span>
                        {!! Form::text('name', '', ['id' => 'name', 'class' => 'form-control', 'required']) !!}
                    </div>
                    <div class="form-group col-sm-6">
                        {!! Form::label('department_id', 'Department') !!}<span class="required">*</span>
                        {!! Form::select('department_id', $departments, null, ['id' => 'department_id', 'class' => 'form-control', 'required']) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('email', 'Email') !!}
                        {!! Form::email('email', '', ['id' => 'email', 'class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('website', 'Website') !!}
                        {!! Form::url('website', '', ['id' => 'website', 'class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="text-right">
                    {!! Form::button('Save', ['type' => 'submit', 'class' => 'btn btn-primary', 'id' => 'btnSave', 'data-loading-text' => "<span class='spinner-border spinner-border-sm'></span> Processing..."]) !!}
                    <button type="button" class="btn btn-light ml-1" data-dismiss="modal">Cancel</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/clients/table.blade.php
<table class="table table-responsive-sm table-striped table-bordered" id="clients_table">
    <thead>
    <tr>
        <th>Name</th>
        <th>Department</th>
        <th>Email</th>
        <th>Website</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody></tbody>
</table>