routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

/*
|--------------------------------------------------------------------------
| Auth Login Route
|--------------------------------------------------------------------------
*/
Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');

Route::post('login', 'Auth\LoginController@login');

Route::get('activate', 'AuthController@verifyAccount');

Route::post('set-password', 'AuthController@setPassword');

Route::group(['middleware' => ['auth', 'validate.user', 'user.activated']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/users-work-report', 'HomeController@workReport')->name('users-work-report');
    Route::get('/developer-work-report', 'HomeController@developerWorkReport')->name('developers-work-report');

    Route::post('logout', 'Auth\LoginController@logout');
    Route::group(['middleware' => ['permission:manage_activities']], function () {
        Route::resource('activity-types', 'ActivityTypeController');
    });

    Route::group(['middleware' => ['permission:manage_clients']], function () {
        Route::resource('clients', 'ClientController');
    });

    Route::group(['middleware' => ['permission:manage_users']], function () {
        Route::post('users/{user}/active-de-active', 'UserController@activeDeActiveUser')
            ->name('active-de-active-user');
        Route::resource('users', 'UserController');
        Route::get('users/{user}/send-email', 'UserController@resendEmailVerification')->name('send-email');
    });

    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::post('users/profile-update', 'UserController@profileUpdate')->name('update-profile');
    Route::post('users/change-password', 'UserController@changePassword')->name('change-password');

    Route::group(['middleware' => ['permission:manage_tags']], function () {
        Route::resource('tags', 'TagController');
    });

    Route::group(['middleware' => ['permission:manage_projects']], function () {
        Route::resource('projects', 'ProjectController');
    });

    Route::group(['middleware' => ['permission:manage_all_tasks']], function () {
        Route::resource('tasks', 'TaskController');
        Route::post('tasks/{task}/update-status', 'TaskController@updateStatus')->name('task.update-status');
        Route::post('tasks/{task}/add-attachment', 'TaskController@addAttachment')->name('task.add-attachment');
        Route::post('tasks/{task_attachment}/delete-attachment', 'TaskController@deleteAttachment')
            ->name('task.delete-attachment');
        Route::get('tasks/{task}/get-attachments', 'TaskController@getAttachment')->name('task.attachments');
        Route::post('tasks/{task}/comments', 'CommentController@addComment')->name('task.comments');
        Route::post(
            'tasks/{task}/comments/{comment}/update',
            'CommentController@editComment'
        )->name('task.update-comment');
        Route::delete(
            'tasks/{task}/comments/{comment}',
            'CommentController@deleteComment'
        )->name('task.delete-comment');
        Route::get('task-details/{task}', 'TaskController@getTaskDetails')->name('task.get-details');
        Route::get('tasks/{task}/comments-count', 'TaskController@getCommentsCount')->name('task.comments-count');
        Route::get('tasks/{task}/users', 'TaskController@getTaskUsers')->name('task.users');
    });

    Route::resource('time-entries', 'TimeEntryController');
    Route::post('time-entries/{time_entry}/update', 'TimeEntryController@update');
    Route::post('start-timer', 'TimeEntryController@getStartTimer');

    Route::group(['middleware' => ['permission:manage_reports']], function () {
        Route::resource('reports', 'ReportController');
        Route::get('users-of-projects', 'ProjectController@users')->name('users-of-projects');
        Route::get('projects-of-client', 'ClientController@projects')->name('projects-of-client');
        Route::get('clients-of-department', 'DepartmentController@clients')->name('clients-of-department');
    });

    Route::get('my-tasks', 'TaskController@myTasks')->name('my-tasks');
    Route::get('user-last-task-work', 'TimeEntryController@getUserLastTask')->name('user-last-task-work');
    Route::get('projects/{project}/tasks', 'TimeEntryController@getTasks')->name('project-tasks');
    Route::get('my-projects', 'ProjectController@getMyProjects')->name('my-projects');

    Route::group(['middleware' => ['permission:manage_roles']], function () {
        Route::resource('roles', 'RoleController');
    });

    Route::group(['middleware' => ['permission:manage_department']], function () {
        Route::resource('departments', 'DepartmentController');
        Route::post('departments/{department}/update', 'DepartmentController@update');
    });
});

Route::fallback(function () {
    abort(\Symfony\Component\HttpFoundation\Response::HTTP_NOT_FOUND);
});

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTaskRequest;
use App\Http\Requests\UpdateTaskRequest;
use App\Models\Task;
use App\Models\TaskAttachment;
use App\Queries\TaskDataTable;
use App\Repositories\TagRepository;
use App\Repositories\TaskRepository;
use DataTables;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

/**
 * Class TaskController.
 */
class TaskController extends AppBaseController
{
    /** @var TaskRepository */
    private $taskRepository;

    public function __construct(TaskRepository $taskRepo)
    {
        $this->taskRepository = $taskRepo;
    }

    /**
     * Display a listing of the Task.
     *
     * @param Request $request
     *
     * @throws Exception
     *
     * @return Factory|View
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return DataTables::of((new TaskDataTable())->get($request->only([
                'name',
                'filter_project',
                'filter_status',
                'filter_user',
                'due_date_filter',
            ])))->editColumn('title', function (Task $task) {
                return $task->prefix_task_number.' '.$task->title;
            })->filterColumn('title', function (Builder $query, $search) {
                $query->where(function (Builder $query) use ($search) {
                    $query->where('title', 'like', "%$search%")
                        ->orWhereRaw(
                            "concat(ifnull(p.prefix,''),'-',ifnull(tasks.task_number,'')) LIKE ?",
                            ["%$search%"]
                        );
                });
            })
                ->make(true);
        }
        $taskData = $this->taskRepository->getTaskData();

        return view('tasks.index')->with($taskData);
    }

    /**
     * Store a newly created Task in storage.
     *
     * @param CreateTaskRequest $request
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function store(CreateTaskRequest $request)
    {
        $input = $request->all();

        $this->taskRepository->store($this->fill($input));

        return $this->sendSuccess('Task created successfully.');
    }

    private function fill($input)
    {
        $input['status'] = (isset($input['status']) && !empty($input['status'])) ? $input['status'] : Task::STATUS_ACTIVE;
        $input['description'] = is_null($input['description']) ? '' : $input['description'];

        return $input;
    }

    /**
     * @param string $slug
     *
     * @return Factory|JsonResponse|View
     */
    public function show($slug)
    {
        if (count(explode('-', $slug)) != 2) {
            return redirect()->back();
        }

        $projectPrefix = explode('-', $slug)[0];
        $taskNumber = explode('-', $slug)[1];

        $task = $this->taskRepository->show($projectPrefix, $taskNumber);
        if (empty($task)) {
            return redirect()->back();
        }

        $taskData = $this->taskRepository->getTaskData();
        $attachmentUrl = url(Task::PATH);

        return view('tasks.show', compact('task', 'attachmentUrl'))->with($taskData);
    }

    /**
     * Show the form for editing the specified Task.
     *
     * @param Task $task
     *
     * @return JsonResponse
     */
    public function edit(Task $task)
    {
        $task->tags;
        $task->project;
        $task->taskAssignee;
        $task->attachments;

        /** @var TagRepository $tagRepo */
        $tagRepo = app(TagRepository::class);
        $data['tags'] = $tagRepo->getTagList();
        $data['task'] = $task;

        return $this->sendResponse($data, 'Task retrieved successfully.');
    }

    /**
     * Update the specified Task in storage.
     *
     * @param Task              $task
     * @param UpdateTaskRequest $request
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function update(Task $task, UpdateTaskRequest $request)
    {
        $input = $request->all();

        $this->taskRepository->update($this->fill($input), $task->id);

        return $this->sendSuccess('Task updated successfully.');
    }

    /**
     * Remove the specified Task from storage.
     *
     * @param Task $task
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function destroy(Task $task)
    {
        if ($task->timeEntries()->count() > 0) {
            return $this->sendError('Task has one or more time entries.');
        }

        $task->update(['deleted_by' => getLoggedInUserId()]);
        $task->delete();

        return $this->sendSuccess('Task deleted successfully.');
    }

    /**
     * @param Task $task
     *
     * @return JsonResponse
     */
    public function updateStatus(Task $task)
    {
        $this->taskRepository->updateStatus($task->id);

        return $this->sendSuccess('Task status Update successfully.');
    }

    /**
     * @param Task    $task
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function getTaskDetails(Task $task, Request $request)
    {
        $taskDetails = $this->taskRepository->getTaskDetails($task->id, $request->all());

        return $this->sendResponse($taskDetails, 'Task retrieved successfully.');
    }

    /**
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function myTasks(Request $request)
    {
        $input = $request->only('project_id');

        $timerDetails = $this->taskRepository->myTasks($input);

        return $this->sendResponse($timerDetails, 'My tasks retrieved successfully.');
    }

    /**
     * @param TaskAttachment $taskAttachment
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function deleteAttachment(TaskAttachment $taskAttachment)
    {
        $this->taskRepository->deleteFile($taskAttachment->id);

        return $this->sendSuccess('File has been deleted successfully.');
    }

    /**
     * @param Task    $task
     * @param Request $request
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function addAttachment(Task $task, Request $request)
    {
        $input = $request->all();

        try {
            $result = $this->taskRepository->uploadFile($task->id, $input['file']);
        } catch (Exception $e) {
            return $this->sendError($e->getMessage(), $e->getCode());
        }

        return $this->sendResponse($result, 'File has been uploaded successfully.');
    }

    /**
     * @param Task $task
     *
     * @return JsonResponse
     */
    public function getAttachment(Task $task)
    {
        $result = $this->taskRepository->getAttachments($task->id);

        return $this->sendResponse($result, 'Task retrieved successfully.');
    }

    /**
     * @param Task $task
     *
     * @return JsonResponse
     */
    public function getCommentsCount(Task $task)
    {
        return $this->sendResponse($task->comments()->count(), 'Comments count retrieved successfully.');
    }

    /**
     * @param Task $task
     *
     * @return array
     */
    public function getTaskUsers(Task $task)
    {
        return $task->taskAssignee->pluck('name', 'id')->toArray();
    }
}

resources/views/tasks/edit_modal.blade.php
<div id="EditModal" class="modal fade" role="dialog" >
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Task</h5>
                <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
            </div>
            {!! Form::open(['id'=>'editForm']) !!}
            <div class="modal-body">
                <div class="alert alert-danger" id="editValidationErrorsBox"style="display: none" ></div>
                {!! Form::hidden('tag_id',null,['id'=>'tagId']) !!}
                <div class="row">
                    <div class="form-group col-sm-6">
                        {!! Form::label('title', 'Title') !!}<span class="required">*</span>
                        {!! Form::text('title', null, ['id'=>'editTitle','class' => 'form-control','required']) !!}
                    </div>
                    <div class="form-group col-sm-6">
                        {!! Form::label('project_id', 'Project') !!}<span class="required">*</span>
                        {!! Form::select('project_id', $projects, null, ['class' => 'form-control','required', 'id' => 'editProjectId', 'placeholder'=>'Select Project']) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-6">
                        {!! Form::label('priority', 'Priority') !!}<span class="required">*</span>
                        {!! Form::select('priority',$priority, null, ['class' => 'form-control','id'=>'editPriority','required']) !!}
                    </div>
                    <div class="form-group col-sm-6">
                        {!! Form::label('status', 'Status') !!}
                        {!! Form::select('status',$taskStatus, null, ['class' => 'form-control','id'=>'editStatus']) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-6">
                        {!! Form::label('due_date', 'Due Date') !!}
                        {!! Form::text('due_date', null, ['id'=>'editDueDate','class' => 'form-control', 'autocomplete' => 'off']) !!}
                    </div>
                    <div class="form-group col-sm-6">
                        {!! Form::label('tags', 'Tags') !!}
                        {!! Form::select('tags[]',[], null, ['class' => 'form-control','id'=>'editTagIds', 'multiple' => true]) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('assign_to', 'Assign To') !!}
                        {!! Form::select('assignees[]',[], null, ['class' => 'form-control','id'=>'editAssignee', 'multiple' => true]) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('description', 'Description') !!}
                        {!! Form::textarea('description', null, ['id' => 'editDesc', 'class' => 'form-control', 'rows' => 5]) !!}
                    </div>
                </div>
                <div class="text-right">
                    {!! Form::button('Save', ['type'=>'submit','class' => 'btn btn-primary','id'=>'btnTaskEditSave','data-loading-text'=>"<span class='spinner-border spinner-border-sm'></span> Processing..."]) !!}
                    <button type="button" class="btn btn-light ml-1" data-dismiss="modal">Cancel</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/tasks/index.blade.php
@extends('layouts.app')
@section('title')
    Tasks
@endsection
@section('page_css')
    <link rel="stylesheet" href="https://rawgit.com/fronteed/iCheck/1.x/skins/all.css">
@endsection
@section('content')
    <div class="container-fluid">
        <div class="animated fadeIn">
            @include('flash::message')
            <div class="page-header">
                <h3 class="page__heading">Tasks</h3>
                <div class="filter-container">
                    <div class="mr-2">
                        <label class="lbl-block"><b>Assign To</b></label>
                        {!!Form::select('drp_users',$assignees,Auth::id(),['id'=>'filter_user','class'=>'form-control','style'=>'min-width:150px;', 'placeholder' => 'All'])  !!}
                    </div>
                    <div class="mr-2">
                        <label class="lbl-block"><b>Project</b></label>
                        {!!Form::select('drp_project',$projects,null,['id'=>'filter_project','class'=>'form-control','style'=>'min-width:150px;', 'placeholder' => 'All'])  !!}
                    </div>
                    <div class="mr-2">
                        <label class="lbl-block"><b>Due Date</b></label>
                        {!! Form::text('due_date_filter', null, ['id'=>'dueDateFilter','class' => 'form-control', 'autocomplete' => 'off','style'=>'min-width:150px;']) !!}
                    </div>
                    <div class="mr-2">
                        <label class="lbl-block"><b>Status</b></label>
                        {!!Form::select('drp_status',$status,0,['id'=>'filter_status','class'=>'form-control','style'=>'min-width:150px;'])  !!}
                    </div>
                    <a href="#" class="btn btn-primary filter-container__btn" data-toggle="modal" data-target="#AddModal"></i>New
                        Task</a>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            @include('tasks.table')
                            <div class="pull-right mr-3">

                            </div>
                        </div>
                        @include('tasks.modal')
                        @include('tasks.edit_modal')
                        @include('tasks.task_details')
                        @include('time_entries.modal')
                        @include('time_entries.edit_modal')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.11.4/standard/ckeditor.js"></script>
@endsection

@section('scripts')
    <script>
        let taskIndexUrl = '{{route('tasks.index')}}';
        let taskUrl = '{{url('tasks')}}/';
        let taskDetailUrl = '{{url('task-details')}}';
        let createTaskUrl = '{{route('tasks.store')}}';
        let timeEntryUrl = "{{url('time-entries')}}/";
        let getTaskUrl = "{{url('get-tasks')}}/";
        let projectsURL = "{{url('projects')}}/";
        let taskStatusJson = '{!! json_encode($taskStatus) !!}';
        let taskStatus = $.parseJSON(taskStatusJson)
        let taskBadgesJson = '{!! json_encode($taskBadges) !!}';
        let taskBadges = $.parseJSON(taskBadgesJson);
        let taskDetailActionColumnIsVisible = true;
        let reportStartDate = '';
        let reportEndDate = '';
        let usersOfProjects = "{{ url('users-of-projects') }}";
        let canManageEntries = "{{ (Auth::user()->can('manage_time_entries')) ? true : false }}";
    </script>
    <script src="{{ mix('assets/js/task/task.js') }}"></script>
    <script src="{{ mix('assets/js/task/task_time_entry.js') }}"></script>
    <script src="{{ mix('assets/js/time_entries/time_entry.js') }}"></script>
@endsection

resources/views/tasks/modal.blade.php
<div id="AddModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">New Task</h5>
                <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
            </div>
            {!! Form::open(['id'=>'addNewForm']) !!}
            <div class="modal-body">
                <div class="alert alert-danger" id="validationErrorsBox" style="display: none"></div>
                <div class="row">
                    <div class="form-group col-sm-6">
                        {!! Form::label('title', 'Title') !!}<span class="required">*</span>
                        {!! Form::text('title', null, ['id'=>'title','class' => 'form-control','required']) !!}
                    </div>
                    <div class="form-group col-sm-6">
                        {!! Form::label('project_id', 'Project') !!}<span class="required">*</span>
                        {!! Form::select('project_id', $projects, null, ['class' => 'form-control','required', 'id' => 'projectId', 'placeholder'=>'Select Project']) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-6">
                        {!! Form::label('priority', 'Priority') !!}<span class="required">*</span>
                        {!! Form::select('priority',$priority, null, ['class' => 'form-control','id'=>'priority','required','placeholder'=>'Select Priority']) !!}
                    </div>
                    <div class="form-group col-sm-6">
                        {!! Form::label('assign_to', 'Assign To') !!}
                        {!! Form::select('assignees[]',[], null, ['class' => 'form-control','id'=>'assignee', 'multiple' => true]) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-6">
                        {!! Form::label('due_date', 'Due Date') !!}
                        {!! Form::text('due_date', null, ['id'=>'dueDate','class' => 'form-control', 'autocomplete' => 'off']) !!}
                    </div>
                    <div class="form-group col-sm-6">
                        {!! Form::label('tags', 'Tags') !!}
                        {!! Form::select('tags[]',$tags, null, ['class' => 'form-control','id'=>'tagIds', 'multiple' => true]) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('description', 'Description') !!}
                        {!! Form::textarea('description', null, ['class' => 'form-control', 'id' => 'description', 'rows' => 5]) !!}
                    </div>
                </div>
                <div class="text-right">
                    {!! Form::button('Save', ['type'=>'submit','class' => 'btn btn-primary','id'=>'btnTaskSave','data-loading-text'=>"<span class='spinner-border spinner-border-sm'></span> Processing..."]) !!}
                    <button type="button" class="btn btn-light ml-1" data-dismiss="modal">Cancel</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/tasks/table.blade.php
<table class="table table-responsive-sm table-striped table-bordered" id="task_table">
    <thead>
    <tr>
        <th></th>
        <th>Title</th>
        <th>Assign To</th>
        <th>Due Date</th>
        <th>Created At</th>
        <th>Reporter</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>

resources/views/tasks/task_details.blade.php
<div id="taskDetailsModal" class="modal fade taskDetailsModal" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content task-detail__model">
            <div class="modal-header">
                <h5 class="modal-title">Task Time Entries</h5>
                <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body task-detail__body">
                @include('loader')
                <div class="row no-gutters time-entry-data">
                    <div class="col-sm-12" id="task-heading"></div>
                    <div class="col-sm-12 mb-2 d-flex">
                        <div class="col-sm-8 pl-0 pt-2" id="total-duration"></div>
                        <div class="col-sm-4 mb-2 pr-0" id="user-drop-down-body">
                            {!!Form::select('task_users',[],null,['id'=>'task_users','class'=>'form-control'])  !!}
                        </div>
                    </div>
                    <table class="col-12 table table-responsive-sm table-striped table-bordered" id="taskDetailsTable">
                        <thead>
                        <tr>
                            <th></th>
                            <th>User</th>
                            <th>Start Time</th>
                            <th>End Time</th>
                            <th>Duration</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
                <div class="alert alert-info" id="no-record-info-msg">No time entries found for this task</div>
            </div>
        </div>
    </div>
</div>

resources/views/tasks/time_tracking_modal.blade.php
<div class="modal fade" id="timeTrackingModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Time Tracking</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body overflow-auto">
                <table class="table table-hover time-tracker-table">
                    <thead>
                    <tr>
                        <th scope="col">Note</th>
                        <th scope="col">Activity</th>
                        <th scope="col">Start Time</th>
                        <th scope="col">End Time</th>
                        <th scope="col" class="text-nowrap text-center">Tracked By</th>
                        <th scope="col" class="text-nowrap text-center">Time</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($task->timeEntries as $entry)
                        <tr>
                            <td>{!! nl2br($entry->note) !!}</td>
                            <td>{{$entry->activityType->name}}</td>
                            <td>{{\Carbon\Carbon::parse($entry->start_time)->format('Y-m-d h:ma')}}</td>
                            <td>{{\Carbon\Carbon::parse($entry->end_time)->format('Y-m-d h:ma')}}</td>
                            <td class="text-nowrap text-center"><img src="{{$entry->user->img_avatar}}" width="40px"> </td>
                            <td class="text-nowrap text-center">{{roundToQuarterHour($entry->duration)}}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>